### PR TITLE
Component/love illustration

### PR DESCRIPTION
**Pull request by admtomas**
Adds the atom that displays 'LOVE' sign , svg paths copied  from the Figma design.
Awaiting review.

### CODE REVIEW

**Comment by mmkobylin** [comment]
Sign 'LOVE' , svg paths copied from sigma. Awaiting review.

**Comment by RobTF9** [comment]
@mmkobylin apologies I didn't notice this. You need to select a reviewer in the top right in future.

**Review by RobTF9 — APPROVED** [review]
LGTM 👍

**Comment by mmkobylin** [comment]
@RobTF9 thanks for the approval, next time I will select a reviewer.

**Pull request merged**
